### ISSUE TITLE
wrong event amount 

### ISSUE THREAD

**Issue by ngc2029** [BFlyFinance/FAI#3]
the mount of event  should be  'withdraw_amount' 
https://github.com/BFlyFinance/FAI/blob/3f94bf2fa6dc8937253b9222a4320557a1608254/sources/modules/pool/STCVaultPoolA.move#L224

**Comment by 6543ngc** [comment]
Yeah, it's a mistake here.

**Comment by 6543ngc** [comment]
#4 
fixed the bug and leave a pull request
